
name: CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t ghcr.io/yash1wi/docker .
      - run: docker push ghcr.io/yash1wi/docker
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: 1072626419
          token: 6749537412:AAEZU5ul2IdN-qCA7hscpkDn1gtycSw8oHA
          location: '55.06904 82.90881'
          venue: '55.06904 82.90881 ШАРАГА'
          message: |
            Автоматизация питон кода сделанная ${{ github.actor }} ещё и коммит:
            ${{ github.event.commits[0].message }}
            
            Репоп ${{ github.repository }}
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker run ghcr.io/yash1wi/docker
  
